In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from tensorflow import constant
import tensorflow as tf
from tensorflow import keras
from tensorflow import feature_column 
from tensorflow import estimator
from tensorflow.keras import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import QuantileTransformer
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from keras.callbacks import EarlyStopping

%matplotlib inline

Using TensorFlow backend.


In [2]:
df = pd.read_csv("iris.csv")

In [3]:
X = np.array(df.drop('species',axis=1))
Y = np.array(df['species'])
Y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [4]:
Le = LabelEncoder()
Le.fit(['setosa', 'virginica', 'versicolor'])
Y_new = Le.transform(Y)
Y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_new, test_size=0.30, random_state=101)

In [6]:
model_keras = Sequential()

# Define the first layer
model_keras.add(keras.layers.Dense(36, activation='relu', input_shape = (4,)))
model_keras.add(keras.layers.Dropout(0.2))
# Add activation function to classifier
model_keras.add(keras.layers.Dense(18, activation='relu'))
model_keras.add(keras.layers.Dropout(0.5))

model_keras.add(keras.layers.Dense(3, activation='softmax'))

# Finish the model compilation
model_keras.compile(optimizer=keras.optimizers.Adam(lr=0.001), 
              loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# Complete the model fit operation
model_keras.fit(X_train, Y_train, epochs=100, batch_size=5, validation_split=0.2)

Train on 84 samples, validate on 21 samples
Epoch 1/100
84/84 [==============================] - 3s 38ms/sample - loss: 1.6517 - accuracy: 0.4643 - val_loss: 0.8652 - val_accuracy: 0.6190
Epoch 2/100
84/84 [==============================] - 0s 2ms/sample - loss: 1.3076 - accuracy: 0.4762 - val_loss: 0.8609 - val_accuracy: 0.5714
Epoch 3/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.0523 - accuracy: 0.5476 - val_loss: 0.8512 - val_accuracy: 0.5714
Epoch 4/100
84/84 [==============================] - 0s 2ms/sample - loss: 1.0851 - accuracy: 0.5238 - val_loss: 0.8072 - val_accuracy: 0.5714
Epoch 5/100
84/84 [==============================] - 0s 2ms/sample - loss: 0.8828 - accuracy: 0.5833 - val_loss: 0.7476 - val_accuracy: 0.5714
Epoch 6/100
84/84 [==============================] - 0s 2ms/sample - loss: 0.7464 - accuracy: 0.6667 - val_loss: 0.7181 - val_accuracy: 0.5714
Epoch 7/100
84/84 [==============================] - 0s 2ms/sample - loss: 0.7574 - accuracy: 0.7

In [7]:
predictions = np.array(model_keras.predict_classes(X_test))

predictions

array([0, 0, 0, 2, 1, 2, 2, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 1,
       1])

In [8]:
new_predictions = Le.inverse_transform(predictions)
new_predictions

array(['setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'virginica', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'versicolor',
       'versicolor'], dtype='<U10')

In [9]:
df3 = pd.DataFrame({'predictions': new_predictions, 'species': Le.inverse_transform(Y_test)})

# Create crosstab: ct
ct3 = pd.crosstab(df3['predictions'], df3['species'])
print(ct3)

species      setosa  versicolor  virginica
predictions                               
setosa           13           0          0
versicolor        0          19          0
virginica         0           1         12


In [10]:
predictions = np.array(model_keras.predict_classes(X_train))

predictions

array([0, 2, 1, 0, 1, 1, 0, 2, 0, 1, 2, 1, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1,
       0, 2, 2, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2,
       2, 2, 0, 1, 2, 0, 0, 2, 2, 0, 1, 0, 2, 2, 0, 2, 1, 1, 2, 0, 2, 0,
       1, 2, 0, 1, 0, 2, 1, 2, 0, 2, 2, 2, 1, 0, 0, 2, 2, 0, 1, 2, 2, 2,
       2, 0, 2, 0, 2, 1, 2, 2, 0, 2, 1, 1, 1, 2, 1, 0, 1])

In [11]:
new_predictions = Le.inverse_transform(predictions)
new_predictions

array(['setosa', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor', 'setosa', 'virginica', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'setosa',
       'setosa', 'setosa', 'versicolor', 'setosa', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'setosa', 'setosa', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor', 'virginica', 'setosa', 'setosa',
       'virginica', 'virginica', 'setosa', 'versicolor', 'setosa',
       'virginica', 'virginica', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'virginica', 'setosa', 'virginica', 'setosa',
       'versicolor', 'virginica', 'setosa', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'virginica', 's

In [12]:
df3 = pd.DataFrame({'predictions': new_predictions, 'species': Le.inverse_transform(Y_train)})

# Create crosstab: ct
ct3 = pd.crosstab(df3['predictions'], df3['species'])
print(ct3)

species      setosa  versicolor  virginica
predictions                               
setosa           37           0          0
versicolor        0          26          0
virginica         0           4         38


In [13]:
Le = LabelEncoder()
Le.fit(['setosa', 'virginica', 'versicolor'])
Y_new = Le.transform(Y)
Y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_new, test_size=0.30, random_state=101)

In [15]:
Y_train_cat = to_categorical(Y_train)
Y_test_cat = to_categorical(Y_test)

In [16]:
early_stopping_monitor = EarlyStopping(patience=4)
model_keras = Sequential()

# Define the first layer
model_keras.add(keras.layers.Dense(36, activation='relu', input_shape = (4,)))
model_keras.add(keras.layers.Dropout(0.2))
# Add activation function to classifier
model_keras.add(keras.layers.Dense(18, activation='relu'))
model_keras.add(keras.layers.Dropout(0.5))

model_keras.add(keras.layers.Dense(3, activation='softmax'))

# Finish the model compilation
model_keras.compile(optimizer = keras.optimizers.Adam(lr=0.001), 
              loss='categorical_crossentropy', metrics=['accuracy'])
# Complete the model fit operation
model_keras.fit(X_train, Y_train_cat, epochs=100, batch_size=5, validation_split=0.2)

Train on 84 samples, validate on 21 samples
Epoch 1/100
84/84 [==============================] - 2s 18ms/sample - loss: 2.0503 - accuracy: 0.2976 - val_loss: 0.9608 - val_accuracy: 0.5714
Epoch 2/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.3844 - accuracy: 0.4405 - val_loss: 0.9284 - val_accuracy: 0.5714
Epoch 3/100
84/84 [==============================] - 0s 2ms/sample - loss: 1.3837 - accuracy: 0.3929 - val_loss: 0.9007 - val_accuracy: 0.5714
Epoch 4/100
84/84 [==============================] - 0s 2ms/sample - loss: 1.2924 - accuracy: 0.3690 - val_loss: 0.8737 - val_accuracy: 0.5714
Epoch 5/100
84/84 [==============================] - 0s 2ms/sample - loss: 0.9957 - accuracy: 0.4524 - val_loss: 0.8639 - val_accuracy: 0.5714
Epoch 6/100
84/84 [==============================] - 0s 2ms/sample - loss: 1.1834 - accuracy: 0.3810 - val_loss: 0.8582 - val_accuracy: 0.5714
Epoch 7/100
84/84 [==============================] - 0s 1ms/sample - loss: 0.9918 - accuracy: 0.5

In [18]:
predictions = np.array(model_keras.predict(X_train))

predictions*100

array([[9.99464188e+01, 5.30442744e-02, 5.41410001e-04],
       [4.21132369e-04, 6.68173075e+00, 9.33178406e+01],
       [1.10351217e+00, 8.39637222e+01, 1.49327650e+01],
       [9.99404678e+01, 5.89883812e-02, 5.51799138e-04],
       [8.94840336e+00, 8.37659378e+01, 7.28566122e+00],
       [1.14879525e+00, 8.17597122e+01, 1.70914955e+01],
       [9.99308472e+01, 6.84410334e-02, 7.11312867e-04],
       [1.94535556e-03, 8.68579102e+00, 9.13122559e+01],
       [9.99805527e+01, 1.93334036e-02, 1.13407274e-04],
       [3.45327187e+00, 8.27137604e+01, 1.38329611e+01],
       [2.81254615e-04, 5.16922903e+00, 9.48304825e+01],
       [1.03634381e+00, 8.24807816e+01, 1.64828796e+01],
       [9.99800491e+01, 1.98325757e-02, 1.18446602e-04],
       [9.99711838e+01, 2.86232308e-02, 1.92248102e-04],
       [2.83905625e-01, 7.35716858e+01, 2.61444092e+01],
       [9.99567184e+01, 4.28698622e-02, 4.08424472e-04],
       [6.30705178e-01, 8.40075378e+01, 1.53617573e+01],
       [8.13218685e-06, 1.83692