In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from tensorflow import constant
import tensorflow as tf
from tensorflow import keras
from tensorflow import feature_column 
from tensorflow import estimator
from tensorflow.keras import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import QuantileTransformer
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from keras.callbacks import EarlyStopping
from tensorflow.kerasras.utils import plot_model

%matplotlib inline

/home/sinisha/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sinisha/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sinisha/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sinisha/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/sinisha/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed

In [2]:
df = pd.read_csv("iris.csv")

In [3]:
X = np.array(df.drop('species',axis=1))
Y = np.array(df['species'])
Y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [4]:
Le = LabelEncoder()
Le.fit(['setosa', 'virginica', 'versicolor'])
Y_new = Le.transform(Y)
Y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_new, test_size=0.30, random_state=101)

In [6]:
model_keras = Sequential()

# Define the first layer
model_keras.add(keras.layers.Dense(36, activation='relu', input_shape = (4,)))
model_keras.add(keras.layers.Dropout(0.2))
# Add activation function to classifier
model_keras.add(keras.layers.Dense(18, activation='relu'))
model_keras.add(keras.layers.Dropout(0.5))

model_keras.add(keras.layers.Dense(3, activation='softmax'))

# Finish the model compilation
model_keras.compile(optimizer=keras.optimizers.Adam(lr=0.001), 
              loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# Complete the model fit operation
model_keras.fit(X_train, Y_train, epochs=100, batch_size=5, validation_split=0.2)

Train on 84 samples, validate on 21 samples
Epoch 1/100
84/84 [==============================] - 2s 22ms/sample - loss: 1.4833 - accuracy: 0.5357 - val_loss: 1.2876 - val_accuracy: 0.5714
Epoch 2/100
84/84 [==============================] - 0s 733us/sample - loss: 1.6456 - accuracy: 0.4048 - val_loss: 0.9938 - val_accuracy: 0.5714
Epoch 3/100
84/84 [==============================] - 0s 690us/sample - loss: 1.1294 - accuracy: 0.4762 - val_loss: 0.9348 - val_accuracy: 0.5714
Epoch 4/100
84/84 [==============================] - 0s 797us/sample - loss: 1.1005 - accuracy: 0.5000 - val_loss: 0.9012 - val_accuracy: 0.5714
Epoch 5/100
84/84 [==============================] - 0s 917us/sample - loss: 1.2084 - accuracy: 0.4643 - val_loss: 0.8607 - val_accuracy: 0.5714
Epoch 6/100
84/84 [==============================] - 0s 662us/sample - loss: 0.9952 - accuracy: 0.5476 - val_loss: 0.8381 - val_accuracy: 0.5714
Epoch 7/100
84/84 [==============================] - 0s 676us/sample - loss: 0.9544 - a

Epoch 57/100
84/84 [==============================] - 0s 513us/sample - loss: 0.3565 - accuracy: 0.8214 - val_loss: 0.3572 - val_accuracy: 0.8571
Epoch 58/100
84/84 [==============================] - 0s 496us/sample - loss: 0.3100 - accuracy: 0.8095 - val_loss: 0.3636 - val_accuracy: 0.8571
Epoch 59/100
84/84 [==============================] - 0s 486us/sample - loss: 0.2874 - accuracy: 0.9048 - val_loss: 0.3537 - val_accuracy: 0.8571
Epoch 60/100
84/84 [==============================] - 0s 532us/sample - loss: 0.3851 - accuracy: 0.7857 - val_loss: 0.3946 - val_accuracy: 0.8095
Epoch 61/100
84/84 [==============================] - 0s 1ms/sample - loss: 0.3341 - accuracy: 0.8929 - val_loss: 0.3313 - val_accuracy: 0.8571
Epoch 62/100
84/84 [==============================] - 0s 869us/sample - loss: 0.2943 - accuracy: 0.8810 - val_loss: 0.3247 - val_accuracy: 0.8571
Epoch 63/100
84/84 [==============================] - 0s 645us/sample - loss: 0.3079 - accuracy: 0.8810 - val_loss: 0.3305 - v

In [7]:
predictions = np.array(model_keras.predict_classes(X_test))

predictions

array([0, 0, 0, 2, 1, 2, 2, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 1,
       1])

In [8]:
new_predictions = Le.inverse_transform(predictions)
new_predictions

array(['setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'virginica', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'versicolor',
       'versicolor'], dtype='<U10')

In [9]:
df3 = pd.DataFrame({'predictions': new_predictions, 'species': Le.inverse_transform(Y_test)})

# Create crosstab: ct
ct3 = pd.crosstab(df3['predictions'], df3['species'])
print(ct3)

species      setosa  versicolor  virginica
predictions                               
setosa           13           0          0
versicolor        0          19          0
virginica         0           1         12


In [10]:
predictions = np.array(model_keras.predict_classes(X_train))

predictions

array([0, 2, 1, 0, 1, 1, 0, 2, 0, 1, 2, 1, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1,
       0, 2, 2, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2,
       2, 2, 0, 1, 2, 0, 0, 2, 2, 0, 1, 0, 2, 2, 0, 2, 1, 1, 2, 0, 2, 0,
       1, 2, 0, 1, 0, 2, 1, 2, 0, 2, 2, 2, 1, 0, 0, 2, 2, 0, 1, 2, 2, 2,
       2, 0, 2, 0, 2, 1, 2, 2, 0, 2, 1, 1, 1, 2, 1, 0, 1])

In [11]:
new_predictions = Le.inverse_transform(predictions)
new_predictions

array(['setosa', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor', 'setosa', 'virginica', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'setosa',
       'setosa', 'setosa', 'versicolor', 'setosa', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'setosa', 'setosa', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor', 'virginica', 'setosa', 'setosa',
       'virginica', 'virginica', 'setosa', 'versicolor', 'setosa',
       'virginica', 'virginica', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'virginica', 'setosa', 'virginica', 'setosa',
       'versicolor', 'virginica', 'setosa', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'virginica', 's

In [12]:
df3 = pd.DataFrame({'predictions': new_predictions, 'species': Le.inverse_transform(Y_train)})

# Create crosstab: ct
ct3 = pd.crosstab(df3['predictions'], df3['species'])
print(ct3)

species      setosa  versicolor  virginica
predictions                               
setosa           37           0          0
versicolor        0          26          0
virginica         0           4         38


In [13]:
Le = LabelEncoder()
Le.fit(['setosa', 'virginica', 'versicolor'])
Y_new = Le.transform(Y)
Y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_new, test_size=0.30, random_state=101)

In [15]:
Y_train_cat = to_categorical(Y_train)
Y_test_cat = to_categorical(Y_test)

In [16]:
early_stopping_monitor = EarlyStopping(patience=4)
model_keras = Sequential()

# Define the first layer
model_keras.add(keras.layers.Dense(36, activation='relu', input_shape = (4,)))
model_keras.add(keras.layers.Dropout(0.2))
# Add activation function to classifier
model_keras.add(keras.layers.Dense(18, activation='relu'))
model_keras.add(keras.layers.Dropout(0.5))

model_keras.add(keras.layers.Dense(3, activation='softmax'))

# Finish the model compilation
model_keras.compile(optimizer = keras.optimizers.Adam(lr=0.001), 
              loss='categorical_crossentropy', metrics=['accuracy'])
# Complete the model fit operation
model_keras.fit(X_train, Y_train_cat, epochs=100, batch_size=5, validation_split=0.2)

Train on 84 samples, validate on 21 samples
Epoch 1/100
84/84 [==============================] - 2s 18ms/sample - loss: 2.0503 - accuracy: 0.2976 - val_loss: 0.9608 - val_accuracy: 0.5714
Epoch 2/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.3844 - accuracy: 0.4405 - val_loss: 0.9284 - val_accuracy: 0.5714
Epoch 3/100
84/84 [==============================] - 0s 2ms/sample - loss: 1.3837 - accuracy: 0.3929 - val_loss: 0.9007 - val_accuracy: 0.5714
Epoch 4/100
84/84 [==============================] - 0s 2ms/sample - loss: 1.2924 - accuracy: 0.3690 - val_loss: 0.8737 - val_accuracy: 0.5714
Epoch 5/100
84/84 [==============================] - 0s 2ms/sample - loss: 0.9957 - accuracy: 0.4524 - val_loss: 0.8639 - val_accuracy: 0.5714
Epoch 6/100
84/84 [==============================] - 0s 2ms/sample - loss: 1.1834 - accuracy: 0.3810 - val_loss: 0.8582 - val_accuracy: 0.5714
Epoch 7/100
84/84 [==============================] - 0s 1ms/sample - loss: 0.9918 - accuracy: 0.5

In [7]:
predictions = np.array(model_keras.predict(X_train))

predictions*100

array([[9.97410355e+01, 2.58947849e-01, 1.04498822e-05],
       [4.23765487e-05, 2.16794705e+00, 9.78320160e+01],
       [9.19663608e-01, 9.47299500e+01, 4.35038042e+00],
       [9.96918945e+01, 3.08101773e-01, 1.36246053e-05],
       [6.58379650e+00, 9.13582001e+01, 2.05800152e+00],
       [6.49128497e-01, 9.04704666e+01, 8.88040161e+00],
       [9.96066132e+01, 3.93368900e-01, 2.52439841e-05],
       [2.72298465e-04, 3.20517969e+00, 9.67945404e+01],
       [9.98876953e+01, 1.12304814e-01, 1.23335872e-06],
       [2.77127552e+00, 9.28820038e+01, 4.34672976e+00],
       [6.06254907e-05, 2.50134230e+00, 9.74986038e+01],
       [4.92937386e-01, 8.97329178e+01, 9.77414513e+00],
       [9.98976135e+01, 1.02390639e-01, 9.48249863e-07],
       [9.98300018e+01, 1.70002639e-01, 3.19305445e-06],
       [1.55264467e-01, 8.34965134e+01, 1.63482208e+01],
       [9.97842560e+01, 2.15725929e-01, 6.50186121e-06],
       [2.77450472e-01, 9.18374634e+01, 7.88508415e+00],
       [8.48529510e-07, 5.05010

In [ ]:
plot_model(
    model_keras, to_file='model.png', show_shapes=False, show_layer_names=True,
    rankdir='TB', expand_nested=False, dpi=96
)