In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from tensorflow import constant
import tensorflow as tf
from tensorflow import keras
from tensorflow import feature_column 
from tensorflow import estimator
from tensorflow.keras import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import QuantileTransformer
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from keras.callbacks import EarlyStopping
from tensorflow.keras.utils import plot_model

%matplotlib inline

Using TensorFlow backend.


In [2]:
df = pd.read_csv("iris.csv")

In [3]:
X = np.array(df.drop('species',axis=1))
Y = np.array(df['species'])
Y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [4]:
Le = LabelEncoder()
Le.fit(['setosa', 'virginica', 'versicolor'])
Y_new = Le.transform(Y)
Y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_new, test_size=0.30, random_state=101)

In [6]:
model_keras = Sequential()

# Define the first layer
model_keras.add(keras.layers.Dense(36, activation='relu', input_shape = (4,)))
model_keras.add(keras.layers.Dropout(0.2))
# Add activation function to classifier
model_keras.add(keras.layers.Dense(18, activation='relu'))
model_keras.add(keras.layers.Dropout(0.5))

model_keras.add(keras.layers.Dense(3, activation='softmax'))

# Finish the model compilation
model_keras.compile(optimizer=keras.optimizers.Adam(lr=0.001), 
              loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# Complete the model fit operation
model_keras.fit(X_train, Y_train, epochs=100, batch_size=5, validation_split=0.2)

Train on 84 samples, validate on 21 samples
Epoch 1/100
84/84 [==============================] - 2s 20ms/sample - loss: 1.5002 - accuracy: 0.3571 - val_loss: 0.8912 - val_accuracy: 0.3810
Epoch 2/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.2437 - accuracy: 0.4643 - val_loss: 0.8329 - val_accuracy: 0.5714
Epoch 3/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.1557 - accuracy: 0.5238 - val_loss: 0.7903 - val_accuracy: 0.5714
Epoch 4/100
84/84 [==============================] - 0s 2ms/sample - loss: 0.9978 - accuracy: 0.5357 - val_loss: 0.7899 - val_accuracy: 0.5714
Epoch 5/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.0622 - accuracy: 0.4524 - val_loss: 0.7892 - val_accuracy: 0.5714
Epoch 6/100
84/84 [==============================] - 0s 1ms/sample - loss: 0.8870 - accuracy: 0.5952 - val_loss: 0.7650 - val_accuracy: 0.5714
Epoch 7/100
84/84 [==============================] - 0s 1ms/sample - loss: 0.8878 - accuracy: 0.5

84/84 [==============================] - 0s 1ms/sample - loss: 0.2923 - accuracy: 0.8571 - val_loss: 0.3491 - val_accuracy: 0.9048
Epoch 58/100
84/84 [==============================] - 0s 858us/sample - loss: 0.2673 - accuracy: 0.8690 - val_loss: 0.3574 - val_accuracy: 0.9048
Epoch 59/100
84/84 [==============================] - 0s 968us/sample - loss: 0.2518 - accuracy: 0.8929 - val_loss: 0.3343 - val_accuracy: 0.8571
Epoch 60/100
84/84 [==============================] - 0s 939us/sample - loss: 0.2758 - accuracy: 0.9048 - val_loss: 0.3307 - val_accuracy: 0.9048
Epoch 61/100
84/84 [==============================] - 0s 847us/sample - loss: 0.3400 - accuracy: 0.8571 - val_loss: 0.3311 - val_accuracy: 0.9048
Epoch 62/100
84/84 [==============================] - 0s 1ms/sample - loss: 0.3237 - accuracy: 0.8571 - val_loss: 0.3205 - val_accuracy: 0.9048
Epoch 63/100
84/84 [==============================] - 0s 1ms/sample - loss: 0.2994 - accuracy: 0.9167 - val_loss: 0.3459 - val_accuracy: 0.90

In [7]:
predictions = np.array(model_keras.predict_classes(X_test))

predictions

array([0, 0, 0, 2, 1, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 1,
       1])

In [8]:
new_predictions = Le.inverse_transform(predictions)
new_predictions

array(['setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'setosa', 'virginica',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa',
       'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'versicolor',
       'versicolor'], dtype='<U10')

In [9]:
df3 = pd.DataFrame({'predictions': new_predictions, 'species': Le.inverse_transform(Y_test)})

# Create crosstab: ct
ct3 = pd.crosstab(df3['predictions'], df3['species'])
print(ct3)

species      setosa  versicolor  virginica
predictions                               
setosa           13           0          0
versicolor        0          20          0
virginica         0           0         12


In [10]:
predictions = np.array(model_keras.predict_classes(X_train))

predictions

array([0, 2, 1, 0, 1, 1, 0, 2, 0, 1, 2, 1, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1,
       0, 2, 2, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2,
       2, 2, 0, 1, 2, 0, 0, 2, 2, 0, 1, 0, 2, 2, 0, 2, 1, 1, 2, 0, 2, 0,
       1, 2, 0, 1, 0, 2, 1, 2, 0, 2, 2, 2, 1, 0, 0, 2, 2, 0, 1, 2, 2, 2,
       2, 0, 2, 0, 2, 1, 2, 2, 0, 2, 1, 1, 1, 2, 1, 0, 1])

In [11]:
new_predictions = Le.inverse_transform(predictions)
new_predictions

array(['setosa', 'virginica', 'versicolor', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor', 'setosa', 'virginica', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'setosa',
       'setosa', 'setosa', 'versicolor', 'setosa', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'setosa', 'setosa', 'virginica', 'virginica', 'virginica',
       'setosa', 'versicolor', 'virginica', 'setosa', 'setosa',
       'virginica', 'virginica', 'setosa', 'versicolor', 'setosa',
       'virginica', 'virginica', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'virginica', 'setosa', 'virginica', 'setosa',
       'versicolor', 'virginica', 'setosa', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'virginica', 's

In [12]:
df3 = pd.DataFrame({'predictions': new_predictions, 'species': Le.inverse_transform(Y_train)})

# Create crosstab: ct
ct3 = pd.crosstab(df3['predictions'], df3['species'])
print(ct3)

species      setosa  versicolor  virginica
predictions                               
setosa           37           0          0
versicolor        0          26          0
virginica         0           4         38


In [13]:
Le = LabelEncoder()
Le.fit(['setosa', 'virginica', 'versicolor'])
Y_new = Le.transform(Y)
Y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_new, test_size=0.30, random_state=101)

In [15]:
Y_train_cat = to_categorical(Y_train)
Y_test_cat = to_categorical(Y_test)

In [19]:
Y_train_cat

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

In [16]:
early_stopping_monitor = EarlyStopping(patience=4)
model_keras = Sequential()

# Define the first layer
model_keras.add(keras.layers.Dense(36, activation='relu', input_shape = (4,)))
model_keras.add(keras.layers.Dropout(0.2))
# Add activation function to classifier
model_keras.add(keras.layers.Dense(18, activation='relu'))
model_keras.add(keras.layers.Dropout(0.5))

model_keras.add(keras.layers.Dense(3, activation='softmax'))

# Finish the model compilation
model_keras.compile(optimizer = keras.optimizers.Adam(lr=0.001), 
              loss='categorical_crossentropy', metrics=['accuracy'])
# Complete the model fit operation
model_keras.fit(X_train, Y_train_cat, epochs=100, batch_size=5, validation_split=0.2)

Train on 84 samples, validate on 21 samples
Epoch 1/100
84/84 [==============================] - 1s 15ms/sample - loss: 2.9426 - accuracy: 0.2500 - val_loss: 1.3644 - val_accuracy: 0.0476
Epoch 2/100
84/84 [==============================] - 0s 1ms/sample - loss: 2.1690 - accuracy: 0.3452 - val_loss: 1.1062 - val_accuracy: 0.1905
Epoch 3/100
84/84 [==============================] - 0s 1ms/sample - loss: 2.1813 - accuracy: 0.3095 - val_loss: 1.0790 - val_accuracy: 0.5714
Epoch 4/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.5778 - accuracy: 0.3333 - val_loss: 1.0984 - val_accuracy: 0.5714
Epoch 5/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.5993 - accuracy: 0.3571 - val_loss: 1.1404 - val_accuracy: 0.5714
Epoch 6/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.2188 - accuracy: 0.5357 - val_loss: 1.0459 - val_accuracy: 0.5714
Epoch 7/100
84/84 [==============================] - 0s 1ms/sample - loss: 1.2440 - accuracy: 0.3

84/84 [==============================] - 0s 1ms/sample - loss: 0.4709 - accuracy: 0.7381 - val_loss: 0.4878 - val_accuracy: 0.7143
Epoch 58/100
84/84 [==============================] - 0s 926us/sample - loss: 0.4107 - accuracy: 0.7738 - val_loss: 0.5059 - val_accuracy: 0.6667
Epoch 59/100
84/84 [==============================] - 0s 938us/sample - loss: 0.4508 - accuracy: 0.7976 - val_loss: 0.4890 - val_accuracy: 0.7143
Epoch 60/100
84/84 [==============================] - 0s 905us/sample - loss: 0.4204 - accuracy: 0.7738 - val_loss: 0.4654 - val_accuracy: 0.7143
Epoch 61/100
84/84 [==============================] - 0s 817us/sample - loss: 0.4027 - accuracy: 0.8571 - val_loss: 0.4581 - val_accuracy: 0.7619
Epoch 62/100
84/84 [==============================] - 0s 934us/sample - loss: 0.4697 - accuracy: 0.7857 - val_loss: 0.4446 - val_accuracy: 0.8095
Epoch 63/100
84/84 [==============================] - 0s 1ms/sample - loss: 0.3724 - accuracy: 0.8690 - val_loss: 0.4495 - val_accuracy: 0.

In [17]:
predictions = np.array(model_keras.predict(X_train))

predictions*100

array([[9.89120865e+01, 1.08638275e+00, 1.53488677e-03],
       [1.73419795e-03, 7.73583221e+00, 9.22624435e+01],
       [1.61639941e+00, 8.52983627e+01, 1.30852299e+01],
       [9.89716263e+01, 1.02697814e+00, 1.39902090e-03],
       [8.22355747e+00, 8.53146667e+01, 6.46178198e+00],
       [1.36710382e+00, 8.11012650e+01, 1.75316296e+01],
       [9.86584930e+01, 1.33926618e+00, 2.24957382e-03],
       [8.69734399e-03, 1.05596218e+01, 8.94316711e+01],
       [9.94234772e+01, 5.76176107e-01, 3.59118916e-04],
       [4.03570986e+00, 8.34446640e+01, 1.25196190e+01],
       [1.85628759e-03, 8.00681210e+00, 9.19913330e+01],
       [1.16501462e+00, 8.13431931e+01, 1.74917927e+01],
       [9.94279404e+01, 5.71722329e-01, 3.45551729e-04],
       [9.93170776e+01, 6.82382107e-01, 5.44200942e-04],
       [4.83662158e-01, 7.11270370e+01, 2.83893013e+01],
       [9.89451828e+01, 1.05345786e+00, 1.35634339e-03],
       [8.26502800e-01, 8.33436508e+01, 1.58298492e+01],
       [1.27846739e-04, 4.23566

In [18]:
plot_model(
    model_keras, to_file='model.png', show_shapes=False, show_layer_names=True,
    rankdir='TB', expand_nested=False, dpi=96
)

"dot" with args ['-Tps', '/tmp/tmpeu851xlr'] returned code: -11

stdout, stderr:
 b''
b'Warning: Could not load "/home/sinisha/miniconda3/lib/graphviz/libgvplugin_pango.so.6" - file not found\n'



AssertionError: -11